/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TSeq extends Token
{
    public TSeq()
    {
        super.setText("/=");
    }

    public TSeq(int line, int pos)
    {
        super.setText("/=");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TSeq(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSeq(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TSeq text.");
    }
}
