/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.analysis;

import minipython.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object in);
    Object getOut(Node node);
    void setOut(Node node, Object out);

    void caseTDef(TDef node);
    void caseTLPar(TLPar node);
    void caseTRPar(TRPar node);
    void caseTEq(TEq node);
    void caseTComma(TComma node);
    void caseTSemi(TSemi node);
    void caseTWhile(TWhile node);
    void caseTFor(TFor node);
    void caseTIn(TIn node);
    void caseTPrint(TPrint node);
    void caseTReturn(TReturn node);
    void caseTMeq(TMeq node);
    void caseTSeq(TSeq node);
    void caseTLBr(TLBr node);
    void caseTRBr(TRBr node);
    void caseTAssert(TAssert node);
    void caseTPlus(TPlus node);
    void caseTMinus(TMinus node);
    void caseTMult(TMult node);
    void caseTDiv(TDiv node);
    void caseTMod(TMod node);
    void caseTDmult(TDmult node);
    void caseTOpen(TOpen node);
    void caseTType(TType node);
    void caseTMax(TMax node);
    void caseTMin(TMin node);
    void caseTAnd(TAnd node);
    void caseTOr(TOr node);
    void caseTNot(TNot node);
    void caseTLess(TLess node);
    void caseTGreat(TGreat node);
    void caseTLesseq(TLesseq node);
    void caseTGreateq(TGreateq node);
    void caseTNoteq(TNoteq node);
    void caseTTrue(TTrue node);
    void caseTFalse(TFalse node);
    void caseTDot(TDot node);
    void caseTTab(TTab node);
    void caseTBlank(TBlank node);
    void caseTId(TId node);
    void caseTLineComment(TLineComment node);
    void caseTString(TString node);
    void caseTNumber(TNumber node);
    void caseEOF(EOF node);
}
